version: "3"

services:

  mailhog:
    image: mailhog/mailhog

  db:
    image: mariadb:10.4
    volumes:
      - "${MOODLE_DOCKER_DBDIR}:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: ${MOODLE_DOCKER_DBNAME}
      MYSQL_USER: ${MOODLE_DOCKER_DBUSER}
      MYSQL_ROOT_PASSWORD: ${MOODLE_DOCKER_DBPASS}
      MYSQL_PASSWORD: ${MOODLE_DOCKER_DBPASS}

  ava:
    image: "moodlehq/moodle-php-apache:7.1"
    volumes:
      - "${MOODLE_DOCKER_APACHE_CONFIG}/apache2_mailhog.conf:/etc/apache2/conf-enabled/apache2_mailhog.conf"
      - "${MOODLE_DOCKER_AVA_WWWROOT}:/var/www/html/ava"
      - "${MOODLE_DOCKER_AVA_DATA}:/var/www/moodledata"
      - "${MOODLE_DOCKER_AVA_CONFIG}:/var/www/html/ava/config.php"
      - "../apps/theme_ledor:/var/www/html/ava/theme/ledor"
    working_dir: /var/www/html/ava/
    env_file:
      - .env
    ports:
      - "${MOODLE_DOCKER_APACHE_PORT}:80"
  #   depends_on:
  #     - mailhog

  dev:
    image: "moodlehq/moodle-php-apache:7.1"
    volumes:
      - "${MOODLE_DOCKER_APACHE_CONFIG}/apache2_mailhog.conf:/etc/apache2/conf-enabled/apache2_mailhog.conf"
      - "${MOODLE_DOCKER_DEV_WWWROOT}:/var/www/html/moodle"
      - "${MOODLE_DOCKER_DEV_DATA}:/var/www/moodledatadev"
      - "${MOODLE_DOCKER_DEV_CONFIG}:/var/www/html/dev/config.php"
      - "../apps/theme_ledor:/var/www/html/dev/theme/ledor"
    working_dir: /var/www/html/dev/
    env_file:
      - .env
    ports:
      - "${MOODLE_DOCKER_APACHE_PORT}:80"
  #   depends_on:
  #     - mailhog

  # memcached:
  #   image: memcached:1.4
  # redis:
  #   image: redis:3

  # solr:
  #   image: solr:6.5
  #   entrypoint:
  #     - docker-entrypoint.sh
  #     - solr-precreate
  #     - test
